/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedOpportunitiesIndexRouteImport } from './routes/_authenticated/opportunities.index'
import { Route as AuthenticatedOpportunitiesIdRouteImport } from './routes/_authenticated/opportunities.$id'
import { Route as ApiPublicHooksSyncOpportunitiesRouteImport } from './routes/api/public/hooks/sync-opportunities'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpportunitiesIndexRoute =
  AuthenticatedOpportunitiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOpportunitiesRoute,
  } as any)
const AuthenticatedOpportunitiesIdRoute =
  AuthenticatedOpportunitiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOpportunitiesRoute,
  } as any)
const ApiPublicHooksSyncOpportunitiesRoute =
  ApiPublicHooksSyncOpportunitiesRouteImport.update({
    id: '/api/public/hooks/sync-opportunities',
    path: '/api/public/hooks/sync-opportunities',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/opportunities/': typeof AuthenticatedOpportunitiesIndexRoute
  '/api/public/hooks/sync-opportunities': typeof ApiPublicHooksSyncOpportunitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/opportunities': typeof AuthenticatedOpportunitiesIndexRoute
  '/api/public/hooks/sync-opportunities': typeof ApiPublicHooksSyncOpportunitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/_authenticated/opportunities/': typeof AuthenticatedOpportunitiesIndexRoute
  '/api/public/hooks/sync-opportunities': typeof ApiPublicHooksSyncOpportunitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/applications'
    | '/chat'
    | '/dashboard'
    | '/opportunities'
    | '/profile'
    | '/recommendations'
    | '/opportunities/$id'
    | '/opportunities/'
    | '/api/public/hooks/sync-opportunities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/applications'
    | '/chat'
    | '/dashboard'
    | '/profile'
    | '/recommendations'
    | '/opportunities/$id'
    | '/opportunities'
    | '/api/public/hooks/sync-opportunities'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/applications'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/opportunities'
    | '/_authenticated/profile'
    | '/_authenticated/recommendations'
    | '/_authenticated/opportunities/$id'
    | '/_authenticated/opportunities/'
    | '/api/public/hooks/sync-opportunities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSyncOpportunitiesRoute: typeof ApiPublicHooksSyncOpportunitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities/': {
      id: '/_authenticated/opportunities/'
      path: '/'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AuthenticatedOpportunitiesIndexRouteImport
      parentRoute: typeof AuthenticatedOpportunitiesRoute
    }
    '/_authenticated/opportunities/$id': {
      id: '/_authenticated/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof AuthenticatedOpportunitiesIdRouteImport
      parentRoute: typeof AuthenticatedOpportunitiesRoute
    }
    '/api/public/hooks/sync-opportunities': {
      id: '/api/public/hooks/sync-opportunities'
      path: '/api/public/hooks/sync-opportunities'
      fullPath: '/api/public/hooks/sync-opportunities'
      preLoaderRoute: typeof ApiPublicHooksSyncOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedOpportunitiesRouteChildren {
  AuthenticatedOpportunitiesIdRoute: typeof AuthenticatedOpportunitiesIdRoute
  AuthenticatedOpportunitiesIndexRoute: typeof AuthenticatedOpportunitiesIndexRoute
}

const AuthenticatedOpportunitiesRouteChildren: AuthenticatedOpportunitiesRouteChildren =
  {
    AuthenticatedOpportunitiesIdRoute: AuthenticatedOpportunitiesIdRoute,
    AuthenticatedOpportunitiesIndexRoute: AuthenticatedOpportunitiesIndexRoute,
  }

const AuthenticatedOpportunitiesRouteWithChildren =
  AuthenticatedOpportunitiesRoute._addFileChildren(
    AuthenticatedOpportunitiesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSyncOpportunitiesRoute: ApiPublicHooksSyncOpportunitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
